#!/bin/bash

# echo "-----> Enabling firewall"
# sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1

# echo "-----> remote login (ssh)"
# silently ignore_error sudo systemsetup -setremotelogin on

# echo "-----> Make mouse and keyboard faster"
# defaults write NSGlobalDomain KeyRepeat -int 0
# defaults write NSGlobalDomain com.apple.mouse.scaling -float 9
# defaults write NSGlobalDomain com.apple.trackpad.scaling -int 9
# defaults write NSGlobalDomain com.apple.scrollwheel.scaling -float 3

echo "-----> Restart automatically if the computer freezes"
sudo systemsetup -setrestartfreeze on

echo "-----> Tweak Finder: Empty trash securely and without prompt, use column view"
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
defaults write com.apple.finder WarnOnEmptyTrash -bool false
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable disk image verification of dmgs
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

echo "-----> Disable natural scrolling"
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# autohide dock, add smart corners that sleep display in both lower section, adjust dock tile size and magnification
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock wvous-bl-corner -integer 10
defaults write com.apple.dock wvous-br-corner -integer 10
defaults write com.apple.dock tilesize -integer 36
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -integer 64

# set ask for password delay to 5 seconds"
defaults write com.apple.screensaver askForPasswordDelay -integer 5

# show all hidden files
defaults write com.apple.finder AppleShowAllFiles YES
defaults write com.apple.finder AppleShowAllExtensions -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

# Remove All Default Apps from Dock
defaults delete com.apple.dock persistent-apps

# Enables Tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -integer 1

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# For now, just the 
defaults write com.Apple.Terminal "Default Window Settings" -string "Pro"
defaults write com.Apple.Terminal "Startup Window Settings" -string "Pro"

defaults write com.apple.screencapture location ~/Dropbox/Screenshots/
defaults write com.apple.screencapture name "Screenshot"

killall Dock
killall Finder
killall SystemUIServer
