#!/bin/sh

# Look into better ways of doing this
# $1 relative file name
sym_linker()
{
	if [ ! -h ~/$1 ]; then
		if [ -f ~/Dropbox/Dotfiles/$1 ]; then
			echo "-----> Symbolically linking file ~/Dropbox/Dotfiles/$1 to ~/$1"
			ln -s ~/Dropbox/Dotfiles/$1 ~/$1
		elif [ -d ~/Dropbox/Dotfiles/$1 ]; then
			echo "-----> Symbolically linking directory ~/Dropbox/Dotfiles/$1 to ~/$1"
			ln -s ~/Dropbox/Dotfiles/$1 ~/$1
		else
			echo "-----> Source file missing at ~/Dropbox/Dotfiles/$1!"
		fi
	fi
}

echo "-----> Dropbox Symlinks"

sym_linker ".bash_history"
sym_linker ".bash_profile"
sym_linker ".bash_secrets"
sym_linker ".bash_aliases"
sym_linker ".gitconfig"
sym_linker ".screenrc"
sym_linker ".ssh/config"
sym_linker "bin"

